### PR TITLE
Loader 0.11.1

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**

### CODE REVIEW

**Comment by TheMadHau5** [comment]
:concern: `sourceCompatdibility`

**Review by BluCobalt — CHANGES_REQUESTED** [review]
looks good but could you fix build it is failing

**Comment by BluCobalt** [comment]
javadocs are breaking build, do we even need them?

**Review by BluCobalt — APPROVED** [review]
Yes this looks good

**Comment by BoogieMonster1O1** [comment]
ok im not waiting

**Pull request merged**
